### ISSUE TITLE
File browser prompt expand/collapse not working

### ISSUE THREAD

**Issue by livlab** [wulkano/kap#368]
**Platform:** MacOS 10.13.3
**Kap Version:** 2.0.0 (2.0.0.681)

### Steps to reproduce
When saving an exported format, the file browser only shows the collapsed version. Attempts to expand to view file list do not produce the file list.
1. After capturing the screen, view the playback
2. select Export GIF from controls on the bottom right of the screen
3. this will reveal the file browser prompt

### Current behaviour
click expor gif shows the file system prompt:
![screen shot 2018-02-01 at 2 02 09 pm](https://user-images.githubusercontent.com/1936365/35697546-83d95662-0758-11e8-85ec-40dfd0f26e63.png)

after clicking arrow down to expand (at the end of Save As line)
![screen shot 2018-02-01 at 2 03 10 pm](https://user-images.githubusercontent.com/1936365/35697605-a9f36e0a-0758-11e8-9a17-34509a572a78.png)

**the screen does not expand to show the contents of the folder.**

### Expected behaviour
After clicking arrow down to expand (at the end of Save As line), screen expands to show file system (as this other example):
![screen shot 2018-02-01 at 2 05 01 pm](https://user-images.githubusercontent.com/1936365/35697713-fd3fe21e-0758-11e8-82b7-359a7ebb973f.png)

### Workaround
Did not encounter a method to expand the screen.

**Comment by timothyis** [comment]
Good catch! Thanks for reporting

**Comment by sindresorhus** [comment]
I'm pretty sure this is fixed in Electron 2.0, which should hopefully be out soon.

**Comment by skllcrn** [comment]
Related to #484

**Comment by sindresorhus** [comment]
I can reproduce this in the latest Kap beta with Electron 3.0.2 and Mojave...

Electron issue: https://github.com/electron/electron/issues/14606

**Comment by skllcrn** [comment]
Still seeing some issues related to this in 3.0.0-beta.5 on Electron 4.

**Comment by skllcrn** [comment]
https://github.com/electron/electron/issues/14606#issuecomment-473524971

**Comment by sindresorhus** [comment]
There is a workaround for this which we should implement in the meantime, seeing as it doesn't look like Electron will fix this anytime soon: https://github.com/electron/electron/commit/24f1eac84f44fd9a7c7e68ea1fc9cd1568e66247
