### ISSUE TITLE
Clicking upgrade notification closes Kap without saving

### ISSUE THREAD

**Issue by LinusU** [wulkano/kap#451]
**Platform:** macOS 10.13.4
**Kap Version:** 2.1.2

### Steps to reproduce

1. Start and finish a recording, keeping the window open and don't save yet
2. Click the notification to get the latest version of Kap
3. Watch your work disappear 😀 

### Current behaviour

1. Simply quits without saving

### Expected behaviour

1. Maybe prompt me to save before closing

### Workaround

1. Think before pressing "Upgrade" 😂

**Comment by maxcell** [comment]
Howdy there! I don't mind taking a stab at this one!

**Comment by albinekb** [comment]
We're not gonna have too many (or any? @skllcrn ) updates to 2.0, so I think this should be fixed in the upcoming 3.0 branch, thoughts @karaggeorge?

**Comment by skllcrn** [comment]
Would love your help on this @maxcell! Thinking it might be easier to do once #450 is merged to `master` and we have a Beta build? Related issue: #481.

**Comment by maxcell** [comment]
@skllcrn That sounds good to me! I don't mind waiting especially if we are changing some big behavior to how the app works. In the meantime, I can get familiar with what we are doing in #450

**Comment by maxcell** [comment]
@skllcrn It seems like the workflow might be slightly different now so it isn't possible to reproduce the error in the latest version. When going and performing a recording it seems as that the new window cropper cannot be reopened while recording (if I'm wrong, please do inform me how to get the bar back). Due to that, one has to stop the recording and when you do and try to get to preferences, it seems like the problem isn't there. However I think #481 could be good to have since there is no real feedback at the moment beyond just being disabled. I do think that the logic with having a notification appear is still valuable, but maybe the test could be changed to say "Latest version" or some other text.

@LinusU If you could check out the latest update and see if the problem still is occurring, please let me know!

**Comment by skllcrn** [comment]
I think I understand what you're getting at @maxcell. In the current version on `master` you can still manually check for updates using the 3-dot more menu in the toolbar of the main app window, and it still doesn't have any feedback which is why #481 is open. 

The question @sindresorhus raised is if we want to be able to manually check for updates at all, which can be addressed in #481. However, wether the update in manual or automatic, we still need to make sure that no work is lost when clicking the update notification. 

With the current `master` version you can have multiple files open at once, which means there can be one or more recordings that need to be exported to avoid losing any work when updating. So if you dismiss an update you need to be able to trigger it again once you've exported the work.

**Comment by maxcell** [comment]
@skllcrn Apologies for asking so many more questions but just want to be sure I fully follow! 😄 

I love what you are saying here, we should make sure that users can 1) once again try to check for updates after it has already been done but also 2) making sure that it doesn't interfere with things currently exporting. That context helps a lot more to understand how to approach solving this. Thank you so much 😄
