### ISSUE TITLE
Can't type numbers beginning with 1 in export size box

### ISSUE THREAD

**Issue by kevincannon** [wulkano/kap#674]
**macOS version:** 10.14.4
**Kap version:**  3.0.0-beta.5
#### Steps to reproduce

- Record a screen grab that's quite big, e.g. 2000+pixels wide.
- Try resize to 1000 pixels wide or any size beginnging with one.

#### Current behaviour
1 changes to 2.
#### Expected behaviour
You can make a number beginning with 1.
#### Workaround
Copy and paste the number you want from a text editor.

![bug_kap_pressing1](https://user-images.githubusercontent.com/5065238/57851208-45dcf900-77e0-11e9-90b9-7275ded1712a.gif)

**Comment by skllcrn** [comment]
Yeah, um, so the good news is that we've fixed it. 😅 Can you grab the [latest beta release](https://github.com/wulkano/kap/releases) @kevincannon?

**Comment by skllcrn** [comment]
Noticed that you're already on the beta @kevincannon, I'd stick to using that if you can, we're not currently planning on doing any updates to earlier versions of Kap. We've re-written Kap from the ground up and we're dedicating all our resources to the upcoming release.

**Comment by kevincannon** [comment]
Sorry, I made a mistake with my bug report.

I see this in the Beta. Using **Version 3.0.0-beta.5** - that's the latest, right?

**Comment by albinekb** [comment]
@kevincannon correct, you can see the latest releases [here](https://github.com/wulkano/kap/releases)

**Comment by kevincannon** [comment]
Thanks!

I made sure I had the latest version and still see this bug though. 😐

**Comment by albinekb** [comment]
I can confirm this is still an issue, can you reopen? I can have a look at this in the weekend :+1:

**Comment by kevincannon** [comment]
@skllcrn - Could you reopen this? We don't have permissions to do that.

**Comment by skllcrn** [comment]
Is this a regression @karaggeorge? I was sure we fixed this in an earlier build.
