### ISSUE TITLE
Unable to export anything after upgrade to 3.2.0

### ISSUE THREAD

**Issue by i-a-n** [wulkano/kap#824]
macOS version: 10.13.6 
Kap version: 3.2.0

Upgrading to v3.2.0 removed all export/destination options after making a screen recording:

<img width="431" alt="Screen Shot 2020-04-14 at 2 58 50 PM" src="https://user-images.githubusercontent.com/1937355/79278857-81a19800-7e61-11ea-9151-773323fd41d0.png">

I reverted back to 3.1.0 and it works again. Running High Sierra on a MBP, nothing unusual/notable about my setup as far as I can tell.

**Comment by karaggeorge** [comment]
Hey, @i-a-n,

I think something is wrong with your app configuration. Easiest way to probably solve it would be deleting `~/Library/Application\ Support/Kap/plugins` and restarting. Note that this will erase all plugins and you'll have to re-install them.

In order to try and debug the issue:
1. did you install any dev version of Kap (from a branch/PR and not stable releases)
2. can you share the contents of `~/Library/Application\ Support/Kap/plugins/package.json` and `~/Library/Application\ Support/Kap/config.json`

Let me know if the above works

**Comment by pog87** [comment]
same issue for me.
deleting all the `~/Library/Application\ Support/Kap/` works as a temp fix: after one use I have to re-delete it and re-configure.

**Comment by rdunk** [comment]
Same thing happening here. I have to remove the `Application Support/Kap` folder before opening Kap otherwise the export format dropdown is empty.

Same versions as OP:
macOS version: 10.13.6
Kap version: 3.2.0

**Comment by karaggeorge** [comment]
Looking into this, if you guys can share the contents of the two files above when you get the error before deleting the directory, that will help a lot

**Comment by pog87** [comment]
there you are!
config.json
```
{
	"kapturesDir": "/Users/username/Movies/Kaptures",
	"allowAnalytics": true,
	"showCursor": true,
	"highlightClicks": false,
	"hideDesktopIcons": false,
	"record60fps": true,
	"loopExports": false,
	"recordKeyboardShortcut": false,
	"doNotDisturb": false,
	"recordAudio": true,
	"audioInputDeviceId": "AppleHDAEngineInput:1B,0,1,0:1",
	"cropper": {
		"x": 0,
		"y": 102,
		"width": 1440,
		"height": 744,
		"ratio": [
			15,
			8
		],
		"displayId": 69732480
	},
	"actionBar": {
		"x": 488,
		"y": 720
	}
}

```

package.json
```
{"dependencies":{}}
```

**Comment by rdunk** [comment]
Bizarre, it was happening consistently until I posted here, now I'm unable to replicate the problem. For what it's worth, I had checked the package.json before deleting previously and it was also empty. If I see it happen again I'll post my config here.

**Comment by karaggeorge** [comment]
Whoever is still having this issue, could you please download and test [this build](https://1542-65411043-gh.circle-artifacts.com/0/dist/Kap.dmg), and let me know if you're still having the issue? The editor will also pop-up a dev tools window, so if you see any errors there please provide them here

**Comment by pog87** [comment]
same identical issue with that build. Console throws error:

```
_app.js:1 Uncaught TypeError: Cannot read property 'find' of undefined
    at c9de51cef6c12f9ed326821698ffca4698cf0587.5e12612144f81b0ca007.js:1
    at Object.o (framework.aec8df86a2709666141f.js:1)
    at p (framework.aec8df86a2709666141f.js:1)
    at framework.aec8df86a2709666141f.js:1
    at y (framework.aec8df86a2709666141f.js:1)
    at at (framework.aec8df86a2709666141f.js:1)
    at lt (framework.aec8df86a2709666141f.js:1)
    at ot (framework.aec8df86a2709666141f.js:1)
    at pt (framework.aec8df86a2709666141f.js:1)
    at L (framework.aec8df86a2709666141f.js:1)
    at W (framework.aec8df86a2709666141f.js:1)
    at Jt (framework.aec8df86a2709666141f.js:1)
    at Gt (framework.aec8df86a2709666141f.js:1)
    at UdKW.t.unstable_runWithPriority (framework.aec8df86a2709666141f.js:1)
    at $l (framework.aec8df86a2709666141f.js:1)
    at F (framework.aec8df86a2709666141f.js:1)
    at Yt (framework.aec8df86a2709666141f.js:1)
    at HTMLDocument.r (_app.js:1)
```

**Comment by karaggeorge** [comment]
Is there any console.log statement in the console before the error? With a message like `Got options from main`? If there is, can you share the json objects following it?

**Comment by karaggeorge** [comment]
@pog87 Can you try this new [build](https://1544-65411043-gh.circle-artifacts.com/0/dist/Kap.dmg) and see if you see that other console log I mentioned and hopefully no error

Sorry for the back and forth, I just haven't been able to reproduce this bug on any of my machines, so I'm unsure what's causing it

**Comment by pog87** [comment]
the error seems to appear after I export to mp4 the 1st time

```
Got options from main Array(4) Array(0) 60

framework.aec8df8….js:1 Uncaught TypeError: Cannot read property 'find' of undefined
    at 6b73418……7e822d68fe03ea.js:1
    at Object.o (framework.aec8df8….js:1)
    at p (framework.aec8df8….js:1)
    at framework.aec8df8….js:1
    at y (framework.aec8df8….js:1)
    at at (framework.aec8df8….js:1)
    at lt (framework.aec8df8….js:1)
    at ot (framework.aec8df8….js:1)
    at pt (framework.aec8df8….js:1)
    at L (framework.aec8df8….js:1)
```

**Comment by karaggeorge** [comment]
So, the first time to export to mp4 it works, and then next time you open a recording you see those options empty? or does it go empty as soon as you click export?

**Comment by pog87** [comment]
Exact, the first time I export to mp4 it works. From the 2nd time I try to export -> empty options

**Comment by gotjoshua** [comment]
I also just came across this issue... 
![HighSierra 10 13 6](https://user-images.githubusercontent.com/8686454/80289999-74768a00-873a-11ea-88b7-8e8cd44b87e1.png)

**Comment by karaggeorge** [comment]
Hey @pog87 and @gotjoshua 

Can you please use this test build and let me know your exact steps and any logs you see in the console: [build](https://1560-65411043-gh.circle-artifacts.com/0/dist/Kap.dmg)

From what I understand you export once for mp4 and then the issue happens. What service do you use to export? Also do you see the issue right after triggering the export does your current open editor show the issue? Or the next editor you open?

Finally, I can't help to notice that all the people having the issue are on 10.13, and it might have something to do with the Swift support libraries not being included to our executables any more for a bunch of packages we use. Can you try downloading those and installing them like mentioned here: https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2

**Comment by karaggeorge** [comment]
I found this issue on Sentry, all 9 of the reported OS versions that reported the error are below 10.14.4 which leads me to believe further that this issue has to do with the swift runtime libraries mentioned above. I'll keep investigating and see what package is causing the issue

**Comment by karaggeorge** [comment]
Update: I think I have tracked down and fixed the bug. If any of you could try this final (hopefully) [build](https://1562-65411043-gh.circle-artifacts.com/0/dist/Kap.dmg), with no console windows or anything like that, just to make sure it's fixed, we'll be able to release it with the next kap version

cc @pog87 @gotjoshua

**Comment by pog87** [comment]
w/ your last build the bug does not seem to reproduce.

Alas, with this version I' m unable to select the input device for audio recording from preferences. :-(

**Comment by karaggeorge** [comment]
Yeah that’s a separate issue that we just fixed in a separate effort. Both of those fixes should hit with the next Kap version

**Comment by gotjoshua** [comment]
greetings, I'll have a look at the next release and confirm that both are fixed. (Sorry I didn't have time to test the extra build)

**Comment by pog87** [comment]
can you link me a working build and the swift tools? thanks!

**Comment by karaggeorge** [comment]
The instructions/tools are here: https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2

The build you can use to test is [this](https://1564-65411043-gh.circle-artifacts.com/0/dist/Kap.dmg)

**Comment by pog87** [comment]
i installed the Swift_5_Runtime_Support_for_Command_Line_Tools but I still cannot select audio source :-(

**Comment by karaggeorge** [comment]
@pog87 we had a small bug that want into the 3.2.1 release. Can you please try using 3.2.2 and see if your issue is resolved?
